### ISSUE TITLE
Crash after the latest commit fd8e1a4

### ISSUE THREAD

**Issue by trmdi** [ishovkun/SierraBreeze#29]
Latest commit fd8e1a4

**Steps to reproduce:**

+ When do not use SierraBreeze: open System Setting > Application style > Window decorations ->> crash

```
Application: System Settings (systemsettings5), signal: Segmentation fault
Using host libthread_db library "/lib64/libthread_db.so.1".
[Current thread is 1 (Thread 0x7ffb72aaacc0 (LWP 11682))]

Thread 7 (Thread 0x7ffb31649700 (LWP 11693)):
#0  0x00007ffb6e1022c9 in poll () from /lib64/libc.so.6
#1  0x00007ffb673442c6 in g_main_context_poll (priority=<optimized out>, n_fds=1, fds=0x7ffb24004a00, timeout=<optimized out>, context=0x7ffb24000bf0) at gmain.c:4204
#2  g_main_context_iterate (context=context@entry=0x7ffb24000bf0, block=block@entry=1, dispatch=dispatch@entry=1, self=<optimized out>) at gmain.c:3898
#3  0x00007ffb673443ec in g_main_context_iteration (context=0x7ffb24000bf0, may_block=may_block@entry=1) at gmain.c:3964
#4  0x00007ffb6ea0fb3b in QEventDispatcherGlib::processEvents (this=0x7ffb24000b20, flags=...) at kernel/qeventdispatcher_glib.cpp:425
#5  0x00007ffb6e9bfb3b in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () at ../../include/QtCore/../../src/corelib/global/qflags.h:140
#6  0x00007ffb6e81e326 in QThread::exec() () at ../../include/QtCore/../../src/corelib/global/qflags.h:120
#7  0x00007ffb6c511085 in QQmlThreadPrivate::run (this=0x55eb77f25e40) at /usr/src/debug/libqt5-qtdeclarative-5.11.1-1.1.x86_64/src/qml/qml/ftw/qqmlthread.cpp:148
#8  0x00007ffb6e8278ec in QThreadPrivate::start(void*) () at thread/qthread_unix.cpp:367
#9  0x00007ffb699f9554 in start_thread () from /lib64/libpthread.so.0
#10 0x00007ffb6e10cccf in clone () from /lib64/libc.so.6

Thread 6 (Thread 0x7ffb33d86700 (LWP 11691)):
#0  0x00007ffb673411eb in g_source_iter_next (iter=iter@entry=0x7ffb33d85ba0, source=source@entry=0x7ffb33d85b98) at gmain.c:982
#1  0x00007ffb67343733 in g_main_context_prepare (context=context@entry=0x7ffb2c000bf0, priority=priority@entry=0x7ffb33d85c20) at gmain.c:944
#2  0x00007ffb673441fb in g_main_context_iterate (context=context@entry=0x7ffb2c000bf0, block=block@entry=1, dispatch=dispatch@entry=1, self=<optimized out>) at gmain.c:3883
#3  0x00007ffb673443ec in g_main_context_iteration (context=0x7ffb2c000bf0, may_block=may_block@entry=1) at gmain.c:3964
#4  0x00007ffb6ea0fb3b in QEventDispatcherGlib::processEvents (this=0x7ffb2c000b20, flags=...) at kernel/qeventdispatcher_glib.cpp:425
#5  0x00007ffb6e9bfb3b in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () at ../../include/QtCore/../../src/corelib/global/qflags.h:140
#6  0x00007ffb6e81e326 in QThread::exec() () at ../../include/QtCore/../../src/corelib/global/qflags.h:120
#7  0x00007ffb6c511085 in QQmlThreadPrivate::run (this=0x55eb77d60dd0) at /usr/src/debug/libqt5-qtdeclarative-5.11.1-1.1.x86_64/src/qml/qml/ftw/qqmlthread.cpp:148
#8  0x00007ffb6e8278ec in QThreadPrivate::start(void*) () at thread/qthread_unix.cpp:367
#9  0x00007ffb699f9554 in start_thread () from /lib64/libpthread.so.0
#10 0x00007ffb6e10cccf in clone () from /lib64/libc.so.6

Thread 5 (Thread 0x7ffb3b9de700 (LWP 11689)):
#0  0x00007ffb6e1022c9 in poll () from /lib64/libc.so.6
#1  0x00007ffb673442c6 in g_main_context_poll (priority=<optimized out>, n_fds=1, fds=0x7ffb34003ce0, timeout=<optimized out>, context=0x7ffb34000bf0) at gmain.c:4204
#2  g_main_context_iterate (context=context@entry=0x7ffb34000bf0, block=block@entry=1, dispatch=dispatch@entry=1, self=<optimized out>) at gmain.c:3898
#3  0x00007ffb673443ec in g_main_context_iteration (context=0x7ffb34000bf0, may_block=may_block@entry=1) at gmain.c:3964
#4  0x00007ffb6ea0fb3b in QEventDispatcherGlib::processEvents (this=0x7ffb34000b20, flags=...) at kernel/qeventdispatcher_glib.cpp:425
#5  0x00007ffb6e9bfb3b in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () at ../../include/QtCore/../../src/corelib/global/qflags.h:140
#6  0x00007ffb6e81e326 in QThread::exec() () at ../../include/QtCore/../../src/corelib/global/qflags.h:120
#7  0x00007ffb6c511085 in QQmlThreadPrivate::run (this=0x55eb72207e30) at /usr/src/debug/libqt5-qtdeclarative-5.11.1-1.1.x86_64/src/qml/qml/ftw/qqmlthread.cpp:148
#8  0x00007ffb6e8278ec in QThreadPrivate::start(void*) () at thread/qthread_unix.cpp:367
#9  0x00007ffb699f9554 in start_thread () from /lib64/libpthread.so.0
#10 0x00007ffb6e10cccf in clone () from /lib64/libc.so.6

Thread 4 (Thread 0x7ffb4395b700 (LWP 11688)):
#0  0x00007ffb6e1022c9 in poll () from /lib64/libc.so.6
#1  0x00007ffb673442c6 in g_main_context_poll (priority=<optimized out>, n_fds=1, fds=0x7ffb3c004a00, timeout=<optimized out>, context=0x7ffb3c000bf0) at gmain.c:4204
#2  g_main_context_iterate (context=context@entry=0x7ffb3c000bf0, block=block@entry=1, dispatch=dispatch@entry=1, self=<optimized out>) at gmain.c:3898
#3  0x00007ffb673443ec in g_main_context_iteration (context=0x7ffb3c000bf0, may_block=may_block@entry=1) at gmain.c:3964
#4  0x00007ffb6ea0fb3b in QEventDispatcherGlib::processEvents (this=0x7ffb3c000b20, flags=...) at kernel/qeventdispatcher_glib.cpp:425
#5  0x00007ffb6e9bfb3b in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () at ../../include/QtCore/../../src/corelib/global/qflags.h:140
#6  0x00007ffb6e81e326 in QThread::exec() () at ../../include/QtCore/../../src/corelib/global/qflags.h:120
#7  0x00007ffb6c511085 in QQmlThreadPrivate::run (this=0x55eb71f1c480) at /usr/src/debug/libqt5-qtdeclarative-5.11.1-1.1.x86_64/src/qml/qml/ftw/qqmlthread.cpp:148
#8  0x00007ffb6e8278ec in QThreadPrivate::start(void*) () at thread/qthread_unix.cpp:367
#9  0x00007ffb699f9554 in start_thread () from /lib64/libpthread.so.0
#10 0x00007ffb6e10cccf in clone () from /lib64/libc.so.6

Thread 3 (Thread 0x7ffb4a1b7700 (LWP 11686)):
#0  0x00007ffb699ff4dc in pthread_cond_wait@@GLIBC_2.3.2 () from /lib64/libpthread.so.0
#1  0x00007ffb4ae7479b in ?? () from /usr/lib64/dri/i965_dri.so
#2  0x00007ffb4ae744c7 in ?? () from /usr/lib64/dri/i965_dri.so
#3  0x00007ffb699f9554 in start_thread () from /lib64/libpthread.so.0
#4  0x00007ffb6e10cccf in clone () from /lib64/libc.so.6

Thread 2 (Thread 0x7ffb5698d700 (LWP 11685)):
#0  QThreadData::canWaitLocked (this=0x55eb718c0780) at ../../include/QtCore/5.11.1/QtCore/private/../../../../../src/corelib/thread/qthread_p.h:255
#1  postEventSourcePrepare (s=0x7ffb50004ba0, timeout=timeout@entry=0x7ffb5698cb84) at kernel/qeventdispatcher_glib.cpp:259
#2  0x00007ffb673437f9 in g_main_context_prepare (context=context@entry=0x7ffb50000bf0, priority=priority@entry=0x7ffb5698cc10) at gmain.c:3475
#3  0x00007ffb673441fb in g_main_context_iterate (context=context@entry=0x7ffb50000bf0, block=block@entry=1, dispatch=dispatch@entry=1, self=<optimized out>) at gmain.c:3883
#4  0x00007ffb673443ec in g_main_context_iteration (context=0x7ffb50000bf0, may_block=may_block@entry=1) at gmain.c:3964
#5  0x00007ffb6ea0fb3b in QEventDispatcherGlib::processEvents (this=0x7ffb50000b20, flags=...) at kernel/qeventdispatcher_glib.cpp:425
#6  0x00007ffb6e9bfb3b in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () at ../../include/QtCore/../../src/corelib/global/qflags.h:140
#7  0x00007ffb6e81e326 in QThread::exec() () at ../../include/QtCore/../../src/corelib/global/qflags.h:120
#8  0x00007ffb6ee60f45 in QDBusConnectionManager::run (this=0x7ffb6f0d6d60 <(anonymous namespace)::Q_QGS__q_manager::innerFunction()::holder>) at qdbusconnection.cpp:178
#9  0x00007ffb6e8278ec in QThreadPrivate::start(void*) () at thread/qthread_unix.cpp:367
#10 0x00007ffb699f9554 in start_thread () from /lib64/libpthread.so.0
#11 0x00007ffb6e10cccf in clone () from /lib64/libc.so.6

Thread 1 (Thread 0x7ffb72aaacc0 (LWP 11682)):
[KCrash Handler]
#6  0x00007ffb6e89c4bc in QString::toIntegral_helper<int> (base=10, ok=0x0, len=<error reading variable: Cannot access memory at address 0x756f00726f6c6f47>, data=<error reading variable: Cannot access memory at address 0x756f00726f6c6f53>) at ../../include/QtCore/../../src/corelib/tools/qstring.h:895
#7  QString::toInt (this=<optimized out>, ok=ok@entry=0x0, base=base@entry=10) at tools/qstring.cpp:7078
#8  0x00007ffb31f7d395 in SierraBreeze::Decoration::readKonsoleProfileColor (this=this@entry=0x55eb7a9a1a60) at /usr/include/qt5/QtCore/qlist.h:115
#9  0x00007ffb31f7dd9e in SierraBreeze::Decoration::reconfigure (this=this@entry=0x55eb7a9a1a60) at /usr/src/debug/sierra-breeze-999.git.1531453864.fd8e1a4-14.1.x86_64/breezedecoration.cpp:321
#10 0x00007ffb31f7dfd0 in SierraBreeze::Decoration::init (this=0x55eb7a9a1a60) at /usr/src/debug/sierra-breeze-999.git.1531453864.fd8e1a4-14.1.x86_64/breezedecoration.cpp:164
#11 0x00007ffb3292d2b3 in ?? () from /usr/lib64/qt5/qml/org/kde/kwin/private/kdecoration/libkdecorationprivatedeclarative.so
#12 0x00007ffb6c50492e in QQmlObjectCreator::finalize(QQmlInstantiationInterrupt&) () at /usr/src/debug/libqt5-qtdeclarative-5.11.1-1.1.x86_64/src/qml/qml/qqmlobjectcreator.cpp:1359
#13 0x00007ffb6c48411a in QQmlIncubatorPrivate::incubate(QQmlInstantiationInterrupt&) () at /usr/src/debug/libqt5-qtdeclarative-5.11.1-1.1.x86_64/src/qml/qml/qqmlincubator.cpp:344
#14 0x00007ffb6c48490a in QQmlIncubationController::incubateFor (this=this@entry=0x55eb77ff33f0, msecs=<optimized out>) at /usr/src/debug/libqt5-qtdeclarative-5.11.1-1.1.x86_64/include/QtQml/5.11.1/QtQml/private/../../../../../src/qml/qml/ftw/qintrusivelist_p.h:216
#15 0x00007ffb6ca76410 in QQuickWindowIncubationController::incubate (this=0x55eb77ff33e0) at /usr/src/debug/libqt5-qtdeclarative-5.11.1-1.1.x86_64/src/quick/items/qquickwindow.cpp:160
#16 QQuickWindowIncubationController::timerEvent (this=0x55eb77ff33e0) at /usr/src/debug/libqt5-qtdeclarative-5.11.1-1.1.x86_64/src/quick/items/qquickwindow.cpp:143
#17 0x00007ffb6e9e93ab in QObject::event(QEvent*) () at kernel/qobject.cpp:1232
#18 0x00007ffb6f9cdc11 in QApplicationPrivate::notify_helper(QObject*, QEvent*) () from /usr/lib64/libQt5Widgets.so.5
#19 0x00007ffb6f9d4df0 in QApplication::notify(QObject*, QEvent*) () from /usr/lib64/libQt5Widgets.so.5
#20 0x00007ffb6e9c0d29 in QCoreApplication::notifyInternal2(QObject*, QEvent*) () at ../../include/QtCore/../../src/corelib/kernel/qobject.h:142
#21 0x00007ffb6ea0f058 in QCoreApplication::sendEvent (event=0x7ffc3d7c3c30, receiver=<optimized out>) at ../../include/QtCore/../../src/corelib/kernel/qcoreapplication.h:234
#22 QTimerInfoList::activateTimers() () at kernel/qtimerinfo_unix.cpp:643
#23 0x00007ffb6ea0f7f4 in timerSourceDispatch (source=<optimized out>) at kernel/qeventdispatcher_glib.cpp:182
#24 0x00007ffb673440be in g_main_dispatch (context=0x7ffb58004ff0) at gmain.c:3177
#25 g_main_context_dispatch (context=context@entry=0x7ffb58004ff0) at gmain.c:3830
#26 0x00007ffb67344358 in g_main_context_iterate (context=context@entry=0x7ffb58004ff0, block=block@entry=1, dispatch=dispatch@entry=1, self=<optimized out>) at gmain.c:3903
#27 0x00007ffb673443ec in g_main_context_iteration (context=0x7ffb58004ff0, may_block=may_block@entry=1) at gmain.c:3964
#28 0x00007ffb6ea0fb23 in QEventDispatcherGlib::processEvents (this=0x55eb71880b90, flags=...) at kernel/qeventdispatcher_glib.cpp:423
#29 0x00007ffb61b25641 in ?? () from /usr/lib64/libQt5XcbQpa.so.5
#30 0x00007ffb6e9bfb3b in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () at ../../include/QtCore/../../src/corelib/global/qflags.h:140
#31 0x00007ffb6e9c78be in QCoreApplication::exec() () at ../../include/QtCore/../../src/corelib/global/qflags.h:120
#32 0x000055eb6fd84aa0 in ?? ()
#33 0x00007ffb6e034feb in __libc_start_main () from /lib64/libc.so.6
#34 0x000055eb6fd84b2a in _start ()

```

+ When using SierraBreeze: Restart the computer > Open any app --> crash. 

@alex47

**Comment by alex47** [comment]
I think I know what the issue is and I'll submit a fix soon...
